### ISSUE TITLE
open_tuner : Japanese version

### ISSUE THREAD

**Issue by shinji-y-jp** [tomvdb/open_tuner#4]
Hello there

I am trying to modify open_tuner for localize Japanese version .
Please watch pics , that's my result .
We are unable to watch the fft window .
Please point out where I have to modify .

Shinji

![opentuner：error：Japanese version](https://user-images.githubusercontent.com/128323883/226206934-6e857c06-0f8e-4478-b6ea-c34b7f52c89e.jpg)
![opentuner：Japanese version](https://user-images.githubusercontent.com/128323883/226206935-479b8fec-9625-4fc3-8dc7-ddfd1b7513c1.jpg)

**Comment by shinji-y-jp** [comment]
Hi there

The modified point :
file        Form1.cs:
            initialConfig.frequency = 1298000;
            initialConfig.symbol_rate = 333;

file        soket.cs:
                /*
                Console.WriteLine(connected);
                Console.WriteLine("Try connect..\n");
                // System.Threading.Thread.Sleep(500);     //can't catch exception from websocket!?, slow down retries if no network

                //ws = new WebSocket("wss://eshail.batc.org.uk/wb/fft", "fft_m0dtslivetune");
                ws = new                 WebSocket("ws://192.168.0.244:7681", "fft_m0dtslivetune");
                ws.OnMessage += (ss, ee) => NewData(ee.RawData);
                ws.OnOpen += (ss, ee) => { connected = true; Console.WriteLine("Connected.\n"); };
                ws.OnClose += (ss, ee) => { connected = false; };
                ws.Connect();
                */ comment outed

Thanks in advance ,

Shinji / JE1BTA

**Comment by tomvdb** [comment]
Hi Shinji,

Thanks for you messages.

(1) The fft display is not from the minitiouner hardware but from the eshail wideband monitor (https://eshail.batc.org.uk/wb/) and it requires an internet connection to work. One of the next updates will be to have a setting that it can be switched off for non eshail use. 

I have a few ideas on doing a more real fft from the hardware or maybe even with the addition of an sdr, but I want to get the basics going on open tuner first.  

If I misunderstood and you actually don't have a working fft with the internet on from the batc site then I'll need to add some more debugging to see whats going on.

(2) Out of interest, what changes do you required for japanese localization? One of the items on my list is to integrate different languages system so that we can load different translations. Is this what you had in mind, or are these specific changes required?

Looking forward to your replies,
Tom - ZR6TG

**Comment by shinji-y-jp** [comment]
Hi Tom,

Thank you for your heartfelt message . I am so glad .
I understood overview of open tuner and your mind .

>what changes do you required for japanese localization?
By the way , Hiroshi JA1SYK who is a pioneer of DVB-S2 in Japan will tell you the Japanese localization detail specs and requirements , that's works well ?
Cos my English ability and understandings about DATV is poor .

>Is this what you had in mind, or are these specific changes required?
The answer is yes . Hope , open tuner prosperity and multilingual working 

With the truth ,

Shinji - JE1BTA

**Comment by shinji-y-jp** [comment]
Hi Tom,

In my words , what Hiroshi saying :
At first 1200MHz band.
Selectable QO-100 mode and Terrestrial mode by button
fft windows :
Center frequency 1298MHz , span 1MHz

These are Hiroshi's requirements .

Thanks a lot ,

Shinji

**Comment by tomvdb** [comment]
Hi Shinji,

I understand the requirement. I'll need to think about best way to implement something like this, but its on the todo list. I'll keep you updated,

Thanks,
Tom

**Comment by shinji-y-jp** [comment]
Hi Tom ,

Thank you for your understandings . In my private opinion , as simple way temporally spec , to enlarge the receiving video windows and not showing spectrum how ?
Cos I know real time fft implementation is hard for us .

Thanks ,

Shinji

**Comment by tomvdb** [comment]
If you look at the latest version you can disable the qo-100 spectrum :

![image](https://user-images.githubusercontent.com/1420347/226827548-2f114dc3-f108-4098-988c-676d17ffbfe3.png)

and then it looks like this

![image](https://user-images.githubusercontent.com/1420347/226827759-759f7e10-788e-40d3-8f67-b1a6e62bf7b3.png)

Is that what you had in mind ?

**Comment by shinji-y-jp** [comment]
Hi Tom ,

Perfect ! I must apologize to you .

Thanks ,

Shinji

**Comment by tomvdb** [comment]
Thanks Shinji! I'll be fixing up the various languages for the next release.

73
